name: MVN Build

on: [push]

jobs:
  mvn-verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: '16'
            distribution: 'zulu'
            architecture: x64
            cache: maven
            arguments: -DskipTests=true
          - java-version: '8'
            distribution: 'zulu'
            architecture: x64
            cache: maven
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ./parsec-testcontainers/parsec_docker_cache
          key: ${{ runner.os }}-parsec_docker_cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-parsec_docker_cache-
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          architecture: ${{ matrix.architecture }}
          cache: ${{ matrix.cache }}
      - name: Build with Maven
        run: ./mvnw --batch-mode clean verify ${{ matrix.arguments }}
